name: 'Starting backend action'
description: 'Starting backend service'
inputs:
  dbuser:
    description: 'dbuser'
    required: true
  dbpassword:
    description: 'dbpassword'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: "zulu"
        architecture: x64
    - name: Setup MySQL DB Server 8.0
      uses: ankane/setup-mysql@v1
      with:
        mysql-version: 8.0
        database: "doughnut_e2e_test"
    - run: |
      mysql -e "CREATE USER '${{ inputs.dbuser}}'@'localhost' IDENTIFIED BY '${{inputs.dbpassword}}'"`);
      mysql -e "GRANT ALL PRIVILEGES ON *.* TO '${{iputs.dbuser}}'@'localhost'"`);
      mysql -e "FLUSH PRIVILEGES"`);
      shell: bash
    - run: yarn sut&
      shell: bash

