image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      git config --global init.defaultBranch main
      rm -rf /home/gitpod/.nvm
      rm -rf /home/gitpod/.sdkman
      rm -rf /home/gitpod/.bashrc.d/50-node
      rm -rf /home/gitpod/.bashrc.d/99-java
      sed -i '/sdkman/d' /home/gitpod/.bashrc
      sed -i '/sdkman/d' /home/gitpod/.bash_profile
      sed -i '/sdkman/d' /home/gitpod/.profile
      sed -i '/NVM_DIR/d' /home/gitpod/.bashrc
      sed -i '/NVM_DIR/d' /home/gitpod/.bash_profile
      sed -i '/NVM_DIR/d' /home/gitpod/.profile
      . /home/gitpod/.bashrc
      . /home/gitpod/.nix-profile/etc/profile.d/nix.sh

ports:
  # Vite Frontend Dev Server
  - port: 5173
    onOpen: open-browser
    visibility: public
  # Springboot Backend Server
  - port: 8081
    onOpen: ignore
  - port: 9081
    onOpen: ignore
    visibility: public
  - port: 9082
    onOpen: ignore
    visibility: public
  # MySQL 8.0 DB Server
  - port: 3309
    onOpen: ignore
  # Remote VNC
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
    visibility: public
  # Mountebank Control Server
  - port: 2525
    visibility: public
  # Mountebank Mock Server
  - port: 5001
    visibility: public

vscode:
  extensions:
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - Vue.volar
    - HansUXdev.bootstrap5-snippets
    - Shelex.vscode-cy-helper
    - mtxr.sqltools
    - GulajavaMinistudio.mayukaithemevsc
    - GabrielBB.vscode-lombok
    - jnoortheen.nix-ide
    - unifiedjs.vscode-mdx
    - ZixuanChen.vitest-explorer
