image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      sudo docker pull registry.jetbrains.team/p/prj/containers/projector-idea-c
    command: |
      sudo mkdir -p .jetbrains; sudo touch .jetbrains/.gitkeep; sudo chown -R 1000:1000 .jetbrains
      sudo docker run --rm -p 8887:8887 -v /workspace/doughnut/.jetbrains:/home/projector-user -it registry.jetbrains.team/p/prj/containers/projector-idea-c
      git config --global init.defaultBranch main
      npm i -g npm yarn
      yarn && cd frontend && yarn && cd -

ports:
  - port: 8887
    visibility: private
    onOpen: open-browser
  - port: 3000
    onOpen: open-preview
  - port: 8081
    onOpen: open-preview
  - port: 9081
    onOpen: open-preview
  - port: 9082
    onOpen: open-preview
  - port: 3309
