image:
  file: .gitpod.Dockerfile

ports:
  # Springboot Backend Server
  - port: 8081
    onOpen: ignore
    visibility: public
  - port: 9081
    onOpen: ignore
    visibility: public
  - port: 9082
    onOpen: ignore
    visibility: public
  # Vite Frontend Dev Server
  - port: 3000
    onOpen: open-browser
    visibility: public
  # MySQL 8.0 DB Server
  - port: 3309
    onOpen: ignore
    visibility: public
  - port: 33090
    onOpen: ignore
  # Remote VNC
  - port: 5900
    onOpen: ignore
    visibility: public
  - port: 6080
    onOpen: open-browser
    visibility: public
  # IntelliJ on Remote VNC
  - port: 8887
    visibility: private
    onOpen: open-browser

tasks:
  - init: |
      mkdir -p /home/gitpod/.config/nix &&
      echo 'sandbox = false' >> /home/gitpod/.config/nix/nix.conf
      sudo docker pull registry.jetbrains.team/p/prj/containers/projector-idea-c
    command: |
      sudo mkdir -p .jetbrains; sudo touch .jetbrains/.gitkeep; sudo chown -R 1000:1000 .jetbrains
      sudo docker run --rm -p 8887:8887 -v /workspace/doughnut/.jetbrains:/home/gitpod -user -it registry.jetbrains.team/p/prj/containers/projector-idea-c

vscode:
  extensions:
    - bbenoist.Nix
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - CoenraadS.bracket-pair-colorizer-2
    - octref.vetur
    - HansUXdev.bootstrap5-snippets
    - vscjava.vscode-spring-initializr
    - vscjava.vscode-spring-boot-dashboard
    - Pivotal.vscode-spring-boot
    - Shelex.vscode-cy-helper
    - xyz.plsql-language
    - vscodevim.vim
    - shd101wyy.markdown-preview-enhanced
    - GulajavaMinistudio.mayukaithemevsc
