image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      git config --global init.defaultBranch main
      rm -rf /home/gitpod/.sdkman
      sed -i '/sdkman/d' /home/gitpod/.bashrc
      sed -i '/sdkman/d' /home/gitpod/.bash_profile
      sed -i '/sdkman/d' /home/gitpod/.profile
      nix develop

ports:
  # Vite Frontend Dev Server
  - port: 3000
    onOpen: open-browser
    visibility: public
  # Springboot Backend Server
  - port: 8081
    onOpen: ignore
  - port: 9081
    onOpen: ignore
    visibility: public
  - port: 9082
    onOpen: ignore
    visibility: public
  # MySQL 8.0 DB Server
  - port: 3309
    onOpen: ignore
    visibility: public
  # Remote VNC
  - port: 5900
    onOpen: ignore
    visibility: public
  - port: 6080
    onOpen: open-browser
    visibility: public

vscode:
  extensions:
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - octref.vetur
    - HansUXdev.bootstrap5-snippets
    - Shelex.vscode-cy-helper
    - xyz.plsql-language
    - bajdzis.vscode-database
    - cweijan.vscode-mysql-client2
    - GulajavaMinistudio.mayukaithemevsc
    - GabrielBB.vscode-lombok
