image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      sudo docker pull registry.jetbrains.team/p/prj/containers/projector-idea-c
      yes | sdk install java 16.0.2-zulu && sdk default java 16.0.2-zulu
      yes | sdk install maven 3.8.3 && sdk default maven 3.8.3
      yes | sdk install gradle 7.2 && sdk default gradle 7.2
      yes | sdk install springboot
      sdk default maven 3.8.3
      sleep 3 && mysql -u root -S /var/run/mysqld/mysqld.sock < infra/gitpod/mysql/init_doughnut_db.sql
      git config --global init.defaultBranch main
      npm i -g npm yarn
      yarn && cd frontend && yarn && cd -
    command: |
      sudo mkdir -p .jetbrains; sudo touch .jetbrains/.gitkeep; sudo chown -R 1000:1000 /workspace/doughnut
      sudo docker run --rm --net=host -p 8887:8887 -v /workspace/doughnut:/home/projector-user -it registry.jetbrains.team/p/prj/containers/projector-idea-c

ports:
  - port: 8887
    visibility: private
    onOpen: open-browser
  # Vite Frontend Dev Server
  - port: 3000
    onOpen: open-browser
    visibility: public
  # Springboot Backend Server
  - port: 8081
    onOpen: ignore
  - port: 9081
    onOpen: ignore
    visibility: public
  - port: 9082
    onOpen: ignore
  # MySQL 8.0 DB Server
  - port: 3309
    onOpen: ignore
  # Remote VNC
  - port: 5900
    onOpen: ignore
    visibility: public
  - port: 6080
    onOpen: open-browser
    visibility: public
