image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      git config --global init.defaultBranch main
      sleep 3 && mysql -u root -S /var/run/mysqld/mysqld.sock < infra/gitpod/mysql/init_doughnut_db.sql
      npm i -g npm yarn
      yarn && cd frontend && yarn && cd -

ports:
  # Vite Frontend Dev Server
  - port: 3000
    onOpen: open-browser
    visibility: public
  # Springboot Backend Server
  - port: 8081
    onOpen: ignore
  - port: 9081
    onOpen: ignore
    visibility: public
  - port: 9082
    onOpen: ignore
    visibility: public
  # MySQL 8.0 DB Server
  - port: 3309
    onOpen: ignore
    visibility: public
  # Remote VNC
  - port: 5900
    onOpen: ignore
    visibility: public
  - port: 6080
    onOpen: open-browser
    visibility: public
  # - port: 8887
  #   onOpen: open-browser
  #   visibility: public

vscode:
  extensions:
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - octref.vetur
    - HansUXdev.bootstrap5-snippets
    - Shelex.vscode-cy-helper
    - xyz.plsql-language
    - bajdzis.vscode-database
    - cweijan.vscode-mysql-client2
    - GulajavaMinistudio.mayukaithemevsc
    - GabrielBB.vscode-lombok
