image:
  file: .gitpod.Dockerfile

ports:
  # Springboot Backend Server
  - port: 8081
    onOpen: ignore
  - port: 9081
    onOpen: ignore
  - port: 9082
    onOpen: ignore
# Vite Frontend Dev Server
  - port: 3000
    onOpen: open-browser
    visibility: public
# MySQL 8.0 DB Server
  - port: 3309
    onOpen: ignore
# Remote VNC
  - port: 5900
    onOpen: ignore
    visibility: public
  - port: 6080
    onOpen: open-browser
    visibility: public

tasks:
  - init: >
      cp infra/gitpod/.zshrc /home/gitpod/ &&
      [ ! -e /home/gitpod/.p10k.zsh ] && cp infra/gitpod/.p10k.zsh /home/gitpod/ &&
      git config --global init.defaultBranch main &&
      sleep 3 && mysql -u root -S /var/run/mysqld/mysqld.sock < infra/gitpod/mysql/init_doughnut_db.sql

vscode:
  extensions:
    - bbenoist.Nix
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - octref.vetur
    - gabrielbb.vscode-lombok
    - HansUXdev.bootstrap5-snippets
    - richardwillis.vscode-gradle
    - Shelex.vscode-cy-helper
    - xyz.plsql-language
    - bajdzis.vscode-database
    - GulajavaMinistudio.mayukaithemevsc
