image:
  file: .gitpod.Dockerfile

ports:
  # Springboot Backend Server
  - port: 8081
    onOpen: ignore
  - port: 9081
    onOpen: ignore
  - port: 9082
    onOpen: ignore
  # Vite Frontend Dev Server
  - port: 3000
    onOpen: open-browser
    visibility: public
  # MySQL 8.0 DB Server
  - port: 3309
    onOpen: ignore
  # Remote VNC
  - port: 5900
    onOpen: ignore
    visibility: public
  - port: 6080
    onOpen: open-browser
    visibility: public

tasks:
  - init: >
      cp infra/gitpod/.zshrc /home/gitpod/ &&
      cp infra/gitpod/.p10k.zsh /home/gitpod/ &&
      git config --global init.defaultBranch main &&
      sudo touch /var/run/mysqld/gitpod-init.lock &&
      test -d /workspace/mysql  || mysqld --initialize-insecure &&
      test -e /var/run/mysqld/mysqld.pid  || mysqld --daemonize &&
      rm -f /var/run/mysqld/gitpod-init.lock &&
      sleep 5 && mysql -u root -S /var/run/mysqld/mysqld.sock < infra/gitpod/mysql/init_doughnut_db.sql

vscode:
  extensions:
    - bbenoist.Nix
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - CoenraadS.bracket-pair-colorizer-2
    - octref.vetur
    - HansUXdev.bootstrap5-snippets
    - vscjava.vscode-spring-initializr
    - vscjava.vscode-spring-boot-dashboard
    - Pivotal.vscode-spring-boot
    - Shelex.vscode-cy-helper
    - xyz.plsql-language
    - bajdzis.vscode-database
    - vscodevim.vim
    - shd101wyy.markdown-preview-enhanced
    - GulajavaMinistudio.mayukaithemevsc
