image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      sudo mkdir -p .jetbrains; sudo touch .jetbrains/.gitkeep; sudo chown -R 1000:1000 .jetbrains
    command: |
      git config --global init.defaultBranch main
      && sleep 3 && mysql -u root -S /var/run/mysqld/mysqld.sock < infra/gitpod/mysql/init_doughnut_db.sql
      && npm i -g npm yarn
      && yarn && cd frontend && yarn && cd -

ports:
  - port: 8887
    visibility: private
    onOpen: open-browser
  - port: 3000
    onOpen: open-preview
  - port: 8081
    onOpen: open-preview
  - port: 9081
    onOpen: open-preview
  - port: 9082
    onOpen: open-preview
  - port: 3309
