name: 'Mobile action'
description: 'Setup flutter stuff'
inputs:
  flutter-version:
    description: 'The Flutter version to make available on the path'
    required: false
  channel:
    description: 'The Flutter build release channel'
    required: false
    default: 'stable'
runs:
  - uses: actions/checkout@v1
  - uses: subosito/flutter-action@v1.5.3
    with:
      flutter-version: ${{ inputs.flutter-version }}
      channel: ${{ inputs.channel }}
  - run: flutter pub get
    working-directory: ./doughnut_mobile
