name: "Setup NodeJS with pnpm cache"
description: "Setup NodeJS with pnpm cache"
inputs:
  node-version:
    description: "NodeJS Version"
    required: true
    default: "21"
runs:
  using: "composite"
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install pnpm
      uses: pnpm/action-setup@v2
        with:
          version: 8.13.0
          run_install: false
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Install dependencies
      run: pnpm --frozen-lockfile recursive install
