name: 'Mobile action'
description: 'Setup flutter stuff'
inputs:
  flutter-version:
    description: 'The Flutter version to make available on the path'
    required: false
  channel:
    description: 'The Flutter build release channel'
    required: false
    default: 'stable'
runs:
  main: 'ls'