name: "Setup NodeJS"
description: "Setup NodeJS"
inputs:
  node-version:
    description: "NodeJS Version"
    required: true
    default: "19.7.0"
runs:
  using: "composite"
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
