name: "Setup NodeJS"
description: "Setup NodeJS"
inputs:
  node-version:
    description: "NodeJS Version"
    required: true
    default: ${{ vars.NODE_VERSION }}
runs:
  using: "composite"
  steps:
    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Setup pnpm & install deps
      uses: pnpm/action-setup@v2
      with:
        version: ${{ vars.PNPM_VERSION }}
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]
