spring:
  profiles:
    active: "test"
  config:
    import: db-test.properties
  resources:
    cache:
      cachecontrol:
        max-age: 365d
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${db.url}
    username: ${db.user}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    clean-on-validation-error: true
  jpa:
    generate-ddl: false
    show-sql: false
    properties.hibernate:
      enable_lazy_load_no_trans: true
  github-for-issues:
    repo: nerds-odd-e/doughnut_sandbox

server:
  forward-headers-strategy: FRAMEWORK
  port: 8081

---
spring:
  profiles: e2e
  resources:
    cache:
      cachecontrol:
        max-age: 365d
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3309/doughnut_e2e_test
    username: doughnut
    password: doughnut
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    clean-on-validation-error: false
    clean-disabled: true
  jpa:
    generate-ddl: false
    show-sql: false
    properties.hibernate:
      enable_lazy_load_no_trans: true
  github-for-issues:
    repo: nerds-odd-e/doughnut_sandbox

server:
  forward-headers-strategy: FRAMEWORK
  port: 9081

---
spring:
  profiles: dev
  resources:
    cache:
      cachecontrol:
        max-age: 365d
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3309/doughnut_development
    username: doughnut
    password: doughnut
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    clean-on-validation-error: false
    clean-disabled: true
  jpa:
    generate-ddl: false
    show-sql: false
    properties.hibernate:
      enable_lazy_load_no_trans: true
  devtools:
    restart:
      additional-paths: static/**,templates/**

server:
  forward-headers-strategy: FRAMEWORK
  port: 9082

---
spring:
  profiles: prod
  resources:
    cache:
      cachecontrol:
        max-age: 365d
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://db-server:3306/doughnut
    username: doughnut
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    clean-on-validation-error: false
    clean-disabled: true
  jpa:
    generate-ddl: false
    show-sql: false
    properties.hibernate:
      enable_lazy_load_no_trans: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${OAUTH2_github_client_id}
            clientSecret: ${OAUTH2_github_client_secret}
  github-for-issues:
    repo: nerds-odd-e/doughnut
server:
  forward-headers-strategy: FRAMEWORK
