spring:
  config:
    activate:
      on-profile: dev
  resources:
    cache:
      cachecontrol:
        max-age: 365d
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/doughnut_development
    username: doughnut
    password: doughnut
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    clean-on-validation-error: false
    clean-disabled: true
  jpa:
    generate-ddl: false
    show-sql: false
    properties.hibernate:
      enable_lazy_load_no_trans: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${OAUTH2_github_client_id_dev}
            clientSecret: ${OAUTH2_github_client_secret_dev}
---
spring:
  config:
    activate:
      on-profile: prod
  resources:
    cache:
      cachecontrol:
        max-age: 365d
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://db-server:3306/doughnut
    username: doughnut
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    clean-on-validation-error: false
    clean-disabled: true
  jpa:
    generate-ddl: false
    show-sql: false
    properties.hibernate:
      enable_lazy_load_no_trans: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${OAUTH2_github_client_id}
            clientSecret: ${OAUTH2_github_client_secret}
            pre-established-redirect-uri: https://doughnut.odd-e.com/login/oauth2/code/github
            registered-redirect-uri: https://doughnut.odd-e.com/login/oauth2/code/github
            use-current-uri: false
server:
  forward-headers-strategy: native
---
spring:
  config:
    import: db-test.properties
  profiles:
    active: test
  resources:
    cache:
      cachecontrol:
        max-age: 365d
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${db.url}
    username: ${db.user}
    password: ${db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    clean-on-validation-error: true
  jpa:
    generate-ddl: false
    show-sql: false
    properties.hibernate:
      enable_lazy_load_no_trans: true
server:
  forward-headers-strategy: native
  port: 8081
