spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/doughnut_development
    username: doughnut
    password: doughnut
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    clean-on-validation-error: true
  jpa:
    generate-ddl: false
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${OAUTH2.github_client_id}
            clientSecret: ${OAUTH2.github_client_secret}