spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/doughnut_development
    username: doughnut
    password: doughnut
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    clean-on-validation-error: true
  jpa:
    generate-ddl: false
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${OAUTH2_github_client_id}
            clientSecret: ${OAUTH2_github_client_secret}
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://db-server:3306/doughnut
    username: doughnut
    password: ${MYSQL_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    clean-on-validation-error: true
  jpa:
    generate-ddl: false
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${OAUTH2_github_client_id}
            clientSecret: ${OAUTH2_github_client_secret}
---
spring:
  config:
    import: db-test.properties
  profiles:
    active: test
  datasource:
    url: ${db.url}
    username: ${db.user}
    password: ${db.password}
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    clean-on-validation-error: true
  jpa:
    generate-ddl: false
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${OAUTH2_github_client_id}
            clientSecret: ${OAUTH2_github_client_secret}
server:
  port: 8081
