# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: dough CI CD

on: push
env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  unit-e2e-tests-run:
    name: Unit & E2E tests
    runs-on: ubuntu-20.04
    #services:
    #  mariadb-server:
    #    image: mariadb:10.3
    #    env:
    #      MYSQL_ROOT_PASSWORD: root
    #      MYSQL_USER: ${{ secrets.DBUSER }}
    #      MYSQL_PASSWORD: ${{ secrets.DBPASSWORD }}
    #      MYSQL_DATABASE: doughnut_test
    #    ports:
    #      - 3306
    #    options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=5
    steps:
      - name: Runs mariadb-server:latest in host
        uses: getong/mariadb-action@v1.1
        with:
          mysql database: 'doughnut_test'
          mysql user: ${{ secrets.DBUSER }}
          mysql password: ${{ secrets.DBPASSWORD }}
      - name: Installs MySQL Client in host
        run: sudo apt-get update && sudo apt-get install -y -f mysql-client
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: x64
      #- name: Unit tests with Gradle
      #  run: backend/gradlew -p backend test -Dspring.profiles.active=test
      - name: E2E tests with Cypress
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn
          wait-on: "http://localhost:8081"
          start: yarn test
      - name: Slack notify dough channel of CI results
        uses: adamkdean/simple-slack-notify@master
        if: always()
        with:
          channel: "#dough"
          status: ${{ job.status }}
          success_text: "dough CI Unit & E2E Tests (#${env.GITHUB_RUN_NUMBER}) completed successfully"
          failure_text: "dough CI Unit & E2E Tests (#${env.GITHUB_RUN_NUMBER}) failed"
          cancelled_text: "dough CI Unit & E2E Tests (#${env.GITHUB_RUN_NUMBER}) was cancelled"
          fields: |
            [{ "title": "Action URL", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"}]

