# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Run e2e test suite on every push to any branch

on: push

jobs:
  cypress-run:
    name: Cypress e2e tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: getong/mariadb-action@v1.1
        with:
          mysql database: "doughnut_test"
          mysql user: ${{ secrets.DBUSER }}
          mysql password: ${{ secrets.DBPASSWORD }}
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: backend
          wrapper-directory: backend
      - uses: cypress-io/github-action@v2
        with:
          install-command: yarn --frozen-lockfile
          wait-on: "http://localhost:8081"
          start: yarn test
