# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Run gradle build and yarn test on push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: debian-latest

    steps:
      - name: Set up JDK 11.0
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: runs gradle build with gradle wrapper in backend/gradle/wrapper dir
      - uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: backend
          wrapper-directory: backend/gradle/wrapper
          arguments: build --args='--spring.profiles.active=test'

  cypress-run:
    runs-on: debian-latest
    steps:
      - name: Run end-to-end tests
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
