# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: dough CI CD

on: push
env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  unit-e2e-tests-run:
    name: Unit & E2E tests
    runs-on: ubuntu-20.04
    #services:
    #  mysql:
    #    image: mariadb:10.5
    #    env:
    #      MYSQL_ROOT_PASSWORD: root
    #      MYSQL_USER: ${{ secrets.DBUSER }}
    #      MYSQL_PASSWORD: ${{ secrets.DBPASSWORD }}
    #      MYSQL_DATABASE: doughnut_test
    #    ports:
    #      - 3306/tcp
    #    options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10
    steps:
      - name: Set up MariaDB Client in host
        run: sudo apt-get update && sudo apt-get install -y mysql-client
      - name: Set up MariaDB 10.5 Server
        uses: ankane/setup-mariadb@v1
        with:
          mariadb-version: 10.5
      - name: Creates Test DB and associated DB user and privileges
        run: mysqladmin create doughnut_test && mysql -e "CREATE USER 'doughnut'@'localhost' IDENTIFIED BY 'doughnut'; GRANT ALL PRIVILEGES ON doughnut_test.* TO 'doughnut'@'localhost';"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: x64
      - name: Unit tests with Gradle
        run: backend/gradlew -p backend test -Dspring.datasource.url='jdbc:mysql://localhost:3306/doughnut_test'
      - name: E2E tests with Cypress
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn
          wait-on: "http://localhost:8081"
          start: yarn test
      - name: Slack notify dough channel of CI results
        uses: adamkdean/simple-slack-notify@master
        if: always()
        with:
          channel: "#dough"
          status: ${{ job.status }}
          success_text: "dough CI Unit & E2E Tests (#${env.GITHUB_RUN_NUMBER}) completed successfully"
          failure_text: "dough CI Unit & E2E Tests (#${env.GITHUB_RUN_NUMBER}) failed"
          cancelled_text: "dough CI Unit & E2E Tests (#${env.GITHUB_RUN_NUMBER}) was cancelled"
          fields: |
            [{ "title": "Action URL", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"}]

