# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Run e2e test suite on every push to any branch

on: push
env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  cypress-run:
    name: Cypress e2e tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: getong/mariadb-action@v1.1
        with:
          mysql database: "doughnut_test"
          mysql user: ${{ secrets.DBUSER }}
          mysql password: ${{ secrets.DBPASSWORD }}
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: cypress-io/github-action@v2
        with:
          install-command: yarn --frozen-lockfile
          wait-on: "http://localhost:8081"
          start: yarn test
      - uses: adamkdean/simple-slack-notify@master
        if: always()
        with:
          channel: "#dough"
          status: ${{ job.status }}
          success_text: "dough CI (#${env.GITHUB_RUN_NUMBER}) completed successfully"
          failure_text: "dough CI (#${env.GITHUB_RUN_NUMBER}) failed"
          cancelled_text: "dough CI (#${env.GITHUB_RUN_NUMBER}) was cancelled"
          fields: |
            [{ "title": "Action URL", "value": "${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"}]
